import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header";
import { Suspense } from "react";
import Footer from "@/components/layout/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Layout UI */}      
        <Suspense fallback="...">
          <Header />
        </Suspense>
        <main className="flex min-h-screen w-full flex-col items-center justify-center py-36">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
